; Pico / Pico W / Pico 2 W + TMC2209 UART + FastAccelStepper
; Use Max Gerhardt platform + FreeRTOS (required by FastAccelStepper on RP2040/RP2350)

[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -D__FREERTOS=1
lib_deps =
    gin66/FastAccelStepper
    teemuatlut/TMCStepper @ ^0.7.3

[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -D__FREERTOS=1
lib_deps =
    gin66/FastAccelStepper
    teemuatlut/TMCStepper @ ^0.7.3

[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -D__FREERTOS=1
lib_deps =
    gin66/FastAccelStepper
    teemuatlut/TMCStepper @ ^0.7.3
